### ISSUE TITLE
Null derefence exception

### ISSUE THREAD

**Issue by rodykersten** [jayhorn/jayhorn#132]
backlog/UnsatNullDereference.java throws an exception from calling the validate() method on a Jimple body: local type not allowed in final code: null_type local: n0

**Comment by martinschaef** [comment]
@rodykersten looks like you forgot to add that file. Could you push it? In general, this can happen if either javac or soot optimize trivial stuff away, but I'll look into it once you pushed it.

**Comment by rodykersten** [comment]
done

**Comment by martinschaef** [comment]
Ok ... like I thought, there is little we can do for this one: if you compile the file, you get the following bytecode:
```
  public static void main(java.lang.String[]);
    descriptor: ([Ljava/lang/String;)V
    flags: ACC_PUBLIC, ACC_STATIC
    Code:
      stack=1, locals=2, args_size=1
         0: aconst_null
         1: astore_1
         2: aload_1
         3: invokevirtual #2                  // Method java/lang/String.length:()I
...
```
If you reconstruct `s` it will be of type `null` and that's not legal. If you don't let it crash, it will just drop the rest of the body including the assertion. 

I ran into that when playing with the CBMC benchmarks and didn't find a good solution other than letting it die. There is no good way of handling this inside jayhorn because you don't get the full bytecode out of soot.

@rodykersten, any thoughts? Maybe throw a more informative exception? Shall we close the issue for now?
