### ISSUE TITLE
Handling of static initializers needs work

### ISSUE THREAD

**Issue by martinschaef** [jayhorn/jayhorn#135]
Rody has an example where our handling of static initializers is unsound. This is nothing new, but we need to work on this to make his benchmark set run through smoothly.

@rodykersten let's create a set of test cases that we can put in the git and then I'll start working on it.

**Comment by rodykersten** [comment]
Turns out that this is not related to static initializers, but rather to how we handle inner classes. I've added a minimal test case in the backlog: UnsatInnerClass.java.

**Comment by rodykersten** [comment]
My last commit fixes UnsatInnerClass, but not the bigger example. I'll look more into that one...

**Comment by rodykersten** [comment]
Committed UnsatIssue135 for which we are still unsound. Haven't figured out why yet...

**Comment by rodykersten** [comment]
This was a tricky one. There is a method that determines whether or not to push on an access of this.field in a constructor. That only pushes if there is not a guaranteed later push, because there is another write to a field of this. The check did not check for writes to this.field, but rather to any usage of the field.
