### ISSUE TITLE
Error not reported

### ISSUE THREAD

**Issue by wuestholz** [jayhorn/jayhorn#25]
When I run the following program it is reported as safe even though the assertion will definitely fail:

```java
public class Test {
    static int c;
    public static void main(String[] args) {
        c = 0;
        assert c == 42;
    }
}
```

**Comment by martinschaef** [comment]
Handling of static fields (and default initialization) is currently broken because we played a bit too hard with the memory model. We'll try to fix this over the weekend or latest next week.

Sorry about that.

**Comment by wuestholz** [comment]
@martinschaef Great! Thank you for the quick reply.

**Comment by martinschaef** [comment]
Fwiw: the bug is that we try to 'pull' the fields of an uninitialized object from the heap. This translates into assume false in the verification condition. You'll observe this behavior quite often when I screw something up.
If you still want to play with the tool until we get this fixed, try the release that we have:
https://github.com/jayhorn/jayhorn/releases/tag/v0.1alpha
That doesn't have the bug. The release can't do much about arrays but should do an ok job on standard examples.

**Comment by wuestholz** [comment]
@martinschaef Thank you for the update. I'll give the release a try for now.

**Comment by martinschaef** [comment]
@wuestholz should work now. Also added your example as regression test:
https://github.com/jayhorn/jayhorn/blob/devel/jayhorn/src/test/resources/horn-encoding/regression/UnsatIssue25.java
to the pre-commit hook.
Please close the issue if you agree.

**Comment by wuestholz** [comment]
@martinschaef Great! Thank you for fixing this.
