### ISSUE TITLE
JayHorn does not detect NullPointerException

### ISSUE THREAD

**Issue by pruemmer** [jayhorn/jayhorn#61]
```
public class Test {
    public int x;
    public static Test a = null;
    public static void main(String[] args) {
        a = null;
        a.x = 42;
    }
}
```

is considered SAFE (when JayHorn is run with option -mem-prec 0)

**Comment by martinschaef** [comment]
Can't reproduce that ... I get a verify exception:

```
com.google.common.base.VerifyException: Cannot find a push that affects this pull. This would introduce an assume(false): $r1_x_02, $r1_$dynamicType_5783 := pull(SatRuntimeException, $r1)
	at com.google.common.base.Verify.verify(Verify.java:123)
	at soottocfg.cfg.util.InterProceduralPullPushOrdering.getFPOsInfluencing(InterProceduralPullPushOrdering.java:180)
	at soottocfg.cfg.util.InterProceduralPullPushOrdering.getPushsInfluencing(InterProceduralPullPushOrdering.java:135)
```

@rodykersten can you take a look?

**Comment by rodykersten** [comment]
@martinschaef you don't get that VerifyException when you set -mem-prec to 0. The VerifyException is caused by #56, which I'm currently working on.

**Comment by rodykersten** [comment]
Ok, so this VerifyException is slightly different from the one in #56. Both are caused by doing a pull of something that was not initialized. In this case, because it is set to null. In the case of #56, because it is an object that is returned by a library call and we do not currently do a push in the stubs (will fix that soon).

I'm not sure how to handle this one. Right now, the left hand side (i.e. declared type) has a classVar for Test, while the rhs has a null classVar. We do a push for Test, then after that we have no way to tell that it actually was not initialized. Perhaps, in the InterproceduralPushPullOrdering, instead of terminating abnormally if there is no push that influences a pull, we should conclude that the program may throw a NullPointerException? In case we have bugs in JayHorn this will give false positives (e.g. until I fix #56), but after that it could work.

**Comment by martinschaef** [comment]
Just added a test case (but accidentally pointed it to #60). If you look at the bytecode, you will see that the exception transformer does not introduce an assertion. The jimple code looks as follows:

```
       <UnsatIssue61: UnsatIssue61 a> = null;
        $r1 = <UnsatIssue61: UnsatIssue61 a>;
        if $r1 == null goto label1;
        $r1.<UnsatIssue61: int x> = 42;
        return;

     label1:
        $helper1 = new java.lang.NullPointerException;
        specialinvoke $helper1.<java.lang.NullPointerException: void <init>()>();
        <JayHornAssertions: java.lang.Throwable lastExceptionThrown> = $helper1;
        return;
```
I'll look into it.

**Comment by pruemmer** [comment]
Now it works, thanks! ;-)

**Comment by rodykersten** [comment]
I think this should not have been closed? The test case still fails. It also fails at code version a158361. Also with -mem-prec=0.
@martinschaef I think this issue might just be everything that you're looking for and more

**Comment by rodykersten** [comment]
Oops my bad, with -rta it works. Why is that not the default?

**Comment by rodykersten** [comment]
But it does not work with the current code...

**Comment by martinschaef** [comment]
Works for me with mem_prec 0 and rta

**Comment by martinschaef** [comment]
Back to your question why `-rta` is off by default. Look at this example:

```java
static void boom(Object o) {
  o.toString();
}

static void main(String[] args) {
  try{boom(null);}
  catch(NullPointerException e) {}
}
```

If `-rta` is switched on, you would get an assertion violation in `boom`. But you don't want that.
