### ISSUE TITLE
Fix constant propagation and dead code elimination.

### ISSUE THREAD

**Issue by martinschaef** [jayhorn/jayhorn#82]
After the inlining, methods a bloated with useless variable renamings. We should have a constant propagation and dead code elimination to clean that up. I tried these old classes:

``` java
CfgUpdater ie = new ExpressionInliner();
CfgUpdater dce = new DeadCodeElimination();
CfgUpdater cp = new ConstantProp();
```

But they don't work anymore. Not sure if it makes sense to fix them. @rodykersten you do a lot of flow stuff, does it make sense to keep them or shall we use some of your code to remove useless assignments?

**Comment by rodykersten** [comment]
Your code has a nice generic visitor structure, while mine is more specialized (simple loops over statements and mostly considers push/pull only). I think it makes sense to keep yours.

**Comment by martinschaef** [comment]
Well ... it's not my code. The guy who wrote it isn't working on this anymore, and the stuff doesn't  work anymore. That's from way back in the days when we didn't have pull and push, so I'm not sure if fixing it makes a lot of sense.

**Comment by rodykersten** [comment]
Now that there's several different classes that do stuff on the CFG level I think it makes sense to refactor that stuff a bit (probably after VMCAI), visitor pattern seems appropriate. For now I guess we can do something similar here as for e.g. PushIdentifierAdder, MissingPushAdder, etc.

**Comment by martinschaef** [comment]
I just relabeled this as a bug because these visitors do strange things. `ExpressionInliner` and `ConstantProp` trigger an assertion because they mix `int` and `java.lang.Integer`. 

`DeadCodeElimination` really breaks stuff. After applying that we can't prove anything. I still haven't figured out why.

**Comment by martinschaef** [comment]
#83 fixes some of this. However, `DeadCodeElimination` only works if we pull the edge labels into the blocks as assume statements. This is troubling because the issue might be the liveVariable analysis. At least the pre-block analysis seems to ignore the variables in the edges. @rodykersten do you use that somewhere, or do you only use the LiveVars computed directly on the method?

`ExpressionInliner` and `ConstantProp` are probably not worth fixing because we'd have to implement all this primitive type boxing/unboxing. @pruemmer @rodykersten any idea what to do with that? Delete? Or add casting for boxed types?

**Comment by martinschaef** [comment]
Could you review [this part](https://github.com/jayhorn/jayhorn/blob/devel/soottocfg/src/main/java/soottocfg/cfg/method/CfgBlock.java#L166) and [this part](https://github.com/jayhorn/jayhorn/blob/devel/soottocfg/src/main/java/soottocfg/cfg/method/CfgBlock.java#L218)? I think I'm right about this. The live variables of a block should contain the variables from incoming and outgoing edges ... its not perfect, but dead code elimination needs the ones from the incoming edges and Horn clause translation needs the one from the outgoing edges...

**Comment by rodykersten** [comment]
I did not write that liveness code... Where is it used?

**Comment by martinschaef** [comment]
@rodykersten  soottocfg.soot.util.FlowBasedPointsToAnalysis.variableFromExpression(Expression)

**Comment by rodykersten** [comment]
DeadCodeElimination only removed edges to CfgBlocks where the label was a false literal. I've added the soottocfg.cfg.optimization.ExpressionEvaluator class to calculate expression return values statically where possible. Right now, it only works with boolean literals (a slight improvement is that it can also deal with expressions over boolean literals now), but we can implement stuff for e.g. integer literals easily. This should use data-flow analysis (probably from Soot) to determine values as well. For instance, it should be able to detect that an object is non-null in order to remove null pointer checks (that would fix SatAliasing01 and 02).

**Comment by rodykersten** [comment]
I've added some Soot optimizations which take care of SatAliasing01 and 02. I'm not sure it makes sense to also implement our own DeadCodeElimination at CFG level... I've also found a class for inlining Jimple methods. How about we just use that one instead of ours, then run the Soot optimizers after that? I'm talking about this class: soot.jimple.toolkits.invoke.SiteInliner

**Comment by rodykersten** [comment]
Hmm I guess if we use that inliner, we miss some methods that JayHorn adds. Maybe stick with what we have for now.

**Comment by martinschaef** [comment]
@rodykersten I'll work on this a bit over the next few days. Do we have a test case where this actually fails?

**Comment by martinschaef** [comment]
I added new classes for this in `soottocfg/src/main/java/soottocfg/cfg/optimization/dataflow/`. They implement the algorithms based on reaching definitions in Apple's book. For SatInstances, they reach the fixpoint too early and fail to propagate some variable. I'll have to look into that.
