### ISSUE TITLE
Currently, we do not use the information that a variable is unique

### ISSUE THREAD

**Issue by martinschaef** [jayhorn/jayhorn#88]
In the cfg, we have the information that if variable is constant or unique. However, this is not used when encoding things as Horn. Hence, we fail to verify the following program:

``` java
class A {
}

class SatCompare {
    public static void main(String[] args) {
        A a1 = new A();
        A a2 = new A();
        assert a1 != a2;
    }
}
```

@pruemmer can you do this? I some other things to work on.

**Comment by martinschaef** [comment]
As part of this: `soottocfg.cfg.variable.Variable.isUnique()` is currently not used anywhere. The translation to Horn should use that.

**Comment by martinschaef** [comment]
I mark this as a bug ... because if you create new Objects in a loop, we still only create one variable ... there is no havoc before or anything.

**Comment by pruemmer** [comment]
Identifying distinct objects is one of the central issues in verification, there is no single good solution for this. (E.g., I know that the Seahorn people are also fighting with this issue). The isUnique flag is not very useful for this, since it is still possible to create new references pointing to old objects. I will see whether we can tune the Horn encoding a bit to take into account that unique variables are at least different from other local variables in scope; but actually this is more a thing to handle on the CFG level. Instead of just assuming that a fresh reference is non-null, an assumption should be created that the reference is distinct from all other references that are in scope.

This does not help in the general case though. There are some natural things we can do to improve precision:
* as discussed earlier, keep track of the allocation site of an object as part of the reference. Objects with different allocation sites have to be distinct; this would immediately solve the SatCompare example above
* keep track of other immutable information about objects, again as part of the reference: dynamic type (already done), size of arrays (already done?), constructor arguments, etc.
* introduce an "allocation counter" that is incremented each time an object is created. The allocation count can again be stored as part of the reference (i.e., we know that an object was the n'th object to be created), and this makes it possible for the Horn solver to identify that some object was created before some other object, and therefore the objects have to be distinct.

**Comment by pruemmer** [comment]
The SatIssue88 example is an interesting case, but I don't see that it would have anything to do with distinctness of objects.

The problem is: somehow our precise memory model is less precise than it should be. In the following CFG, the push with id 2 is shadowed by the push with id 3, but in line 18 both pushes are considered. The case `lastpush == 2` should not be in line 18?

If I manually remove the `lastpush == 2` from the clauses, the problem becomes sat. Then apparently the Horn solver is able to detect that the `Environment` ctor will never throw an exception, therefore the `env` field is non-null after push 3, and everything is fine.

(also, there is no need to `push` in line 18, no variable has been changed after the last pull)

```
Method <Actions: void <init>()>($in_0)
  Return types: java.lang.Throwable
  Returns: java.lang.Throwable $ex_

  locals:
    $r1:    MinePumpSystem.Environment
    $helper8:    java.lang.Throwable
    r0:    Actions
    r0_env_3280:    MinePumpSystem.Environment
    r0_$dynamicType_5511:    java.lang.Class
    $new2:    MinePumpSystem.Environment
    lastpush:    int
Block0:
(ln 8)	lastpush := 3
(ln 8)	push(Actions, r0, [r0_env_3280, r0_$dynamicType_5511, lastpush])
	return
Root ->Block1:
(ln -1)	$this_ := $in_0
(ln -1)	$ex_ := $null$
(ln 6)	r0 := $this_
(ln 6)	r0_$dynamicType_5511 := Actions
(ln 6)	lastpush := 2
(ln 6)	push(Actions, r0, [r0_env_3280, r0_$dynamicType_5511, lastpush])
(ln 7)	$ex_ := call <java.lang.Object: void <init>()>(r0)
(ln 8)	assume ($new2 != $null$)
(ln 8)	$r1 := $new2
(ln 8)	$ex_ := call <MinePumpSystem.Environment: void <init>()>($r1)
(ln 8)	$helper8 := $ex_
	goto:
	  if ($helper8 != $null$): Block2
	  if (!($helper8 != $null$)): Block3
Block2:
	goto:
	  Block0
Block3:
(ln 8)	r0_env_3280 := $r1
	goto:
	  Block0

Method <Actions: void waterRise()>($in_0)
  Return types: java.lang.Throwable
  Returns: java.lang.Throwable $ex_

  locals:
    $assert_2:    boolean
    $r1:    MinePumpSystem.Environment
    r0:    Actions
    $helper9:    java.lang.Throwable
    r0_env_3280:    MinePumpSystem.Environment
    r0_$dynamicType_5511:    java.lang.Class
    lastpush:    int
Block0:
	return
Root ->Block1:
(ln -1)	$this_ := $in_0
(ln -1)	$ex_ := $null$
(ln 17)	r0 := $this_
(ln 18)	r0_env_3280, r0_$dynamicType_5511, lastpush := pull(Actions, r0)
(ln 18)	assume ((((lastpush == 11) || (lastpush == 2)) || (lastpush == 3)) || (lastpush == 4))
(ln 18)	$r1 := r0_env_3280
(ln 18)	$assert_2 := ($r1 != $null$)
(ln 18)	assert $assert_2
(ln 18)	lastpush := 4
(ln 18)	push(Actions, r0, [r0_env_3280, r0_$dynamicType_5511, lastpush])
```

**Comment by martinschaef** [comment]
Interesting indeed. However, the memory model can only detect that `lastpush == 2` cannot happen if it has a way of figuring out that the path where the constructor throws an exception is not feasible.
I was hoping that the theorem prover can handle that but we can certainly do some simplification beforehand. @rodykersten, let's talk about that later.

Let's split up the other work. I want to do this reference as tuple business (but I had to fix soundness bugs the last few days first). 
@pruemmer I also thought about the allocation counter but that is better done in the to-Horn translation. Could you look into this? I'll provide you a literal for stuff that is created with `new`, so every time you translate one of those, you can increment the counter.

**Comment by rodykersten** [comment]
@pruemmer we do these two things already as part of the points to analysis:
-     as discussed earlier, keep track of the allocation site of an object as part of the reference. Objects with different allocation sites have to be distinct; this would immediately solve the SatCompare example above
-     introduce an "allocation counter" that is incremented each time an object is created. The allocation count can again be stored as part of the reference (i.e., we know that an object was the n'th object to be created), and this makes it possible for the Horn solver to identify that some object was created before some other object, and therefore the objects have to be distinct.

At each allocation, I create a new alias ID. We store this alias ID in the set of objects the variable to which it is assigned may point to. Next, we propagate these points to sets. Does it make sense to use these alias IDs instead of 'lastpush'? The last push is indiscriminatory w.r.t. the two allocations in SatCompare, since the push is the same one for both allocations. The alias ID is more precise.

**Comment by rodykersten** [comment]
When you run this SatIssue88 example with mem-prec 0, you see that actually having a push at line 6 makes sense. Namely, there is a path for which there is no push to 'this' after that one. That path is when the superclass constructor throws an exception.
```
Block0:
	return
Root ->Block1:
(ln -1)	$this_ := $in_0
(ln -1)	$ex_ := $null$
(ln 6)	r0 := $this_
(ln 6)	r0_$dynamicType_5941 := Actions
(ln 6)	push(Actions, r0, [r0_env_3540, r0_$dynamicType_5941])
(ln 7)	$ex_ := call <java.lang.Object: void <init>()>(r0)
(ln 8)	$r1 := $new2
(ln 8)	assume ($r1 != $null$)
(ln 8)	$ex_ := call <MinePumpSystem.Environment: void <init>()>($r1)
(ln 8)	$helper1 := $ex_
	goto:
	  if ($helper1 != $null$): Block2
	  if (!($helper1 != $null$)): Block3
Block2:
	goto:
	  Block0
Block3:
(ln 8)	r0_env_3540 := $r1
(ln 8)	push(Actions, r0, [r0_env_3540, r0_$dynamicType_5941])
	goto:
	  Block0
```

**Comment by rodykersten** [comment]
With Martin's last commit this one works for me. Don't know why you get a time out? It's very fast for me.

**Comment by martinschaef** [comment]
Actually, the timeout happened in a different example ... at that was because it took more than 5 sec. So, never mind. My last commit fixes a few examples but does not solve the issue yet: for other minepump examples I still get unsat.

**Comment by martinschaef** [comment]
Closed in caller_id branch. Will merge back into devel soon.
