### ISSUE TITLE
Stubbing generates code that mixes bool and int types

### ISSUE THREAD

**Issue by lememta** [jayhorn/jayhorn#98]
Let's not confuse bool and int :)

**Comment by martinschaef** [comment]
To be more precise, @lememta is complaining about [this example](https://github.com/jayhorn/jayhorn/blob/devel/jayhorn/src/test/resources/horn-encoding/backlog/TypeCheckingIssue98.java).

The issue is that `nextBoolean` returns an `int` instead of a `bool` on the Horn level. Note that on the cfg level the method actually returns a `bool` so the problem is introduced later down the pipeline.

This is a bit of a fuckup where we broke the architecture by hacking stuff for the deadline: Methods currently have a `returnType`, which is a list of `Type` objects, and `outParams` which are variables. The `returnType` is what we get from soot plus one variable that holds the exceptional return value. The `outParams` are the variable which are used inside the body of a method to represent the outgoing stuff. `outParams` hence are only generated for methods with a body.

Now for @lememta example, the method `nextBoolean` doesn't have a body. But since we stub everything, it gets a body (presumably from @rodykersten's code) and this is where the types disagree.

@lememta already pointed to [this code] (https://github.com/jayhorn/jayhorn/blob/devel/jayhorn/src/main/java/jayhorn/hornify/HornEncoderContext.java#L74) where we mix the `outParams` and return types. This place should certainly only use the return types. However, fixing this is not sufficient since the generated body of `nextBoolean` will still mix `int` and `bool`. 

@rodykersten where do you generate the bodies for JDK stuff? Can we go through that on Monday and quickly fix it to make sure that @lememta can continue his spacer stuff?

**Comment by rodykersten** [comment]
This is done in soottocfg.cfg.util.CfgStubber. I can have a look at that later today.

**Comment by rodykersten** [comment]
I fixed the problem in the CfgStubber.

**Comment by martinschaef** [comment]
@lememta is the problem gone? If not, can you give us another example? If it works now, please close the issue.

**Comment by lememta** [comment]
This is working now.
